### PR TITLE
Optional ShouldQueue Behavior

### PR DESCRIPTION
**Pull request by volkv**
Added a simple config option to use alternative Listeners without ShouldQueue interface

### CODE REVIEW

**Comment by volkv** [comment]
Oops, sorry for code style changing 😮

**Comment by antonkomarev** [comment]
@volkv check [my comment](https://github.com/cybercog/laravel-love/issues/139#issuecomment-581418249) for my vision how it should be done. There is no need to make so many changes.

1. `'queue_connection' => null,` in Love's config file to use default queue connection
2. Publish this config file to your app and change this value to `sync`
3. Find a way how to force listener to use value from the config

**Comment by volkv** [comment]
@antonkomarev yes, got a way. will rePR ;)

**Comment by antonkomarev** [comment]
There is no need to create separate Listener without ShouldQueue interface. I'm sure there is a way how we could set queue connection to `sync` on the fly.

**Comment by antonkomarev** [comment]
Closing in favor of https://github.com/cybercog/laravel-love/issues/145#issuecomment-583730266

**Pull request closed without merging**
