### PR TITLE
Extract local Model scopes to Eloquent Builder traits

### PR DESCRIPTION
**Pull request by antonkomarev**
**This is breaking change!**

- Resolves #226 
- [Solution 2 implementation](https://github.com/cybercog/laravel-love/discussions/226#discussioncomment-4612667)

Reactable trait methods `scopeWhereReactedBy`, `scopeWhereNotReactedBy`, `scopeJoinReactionCounterOfType`, `scopeJoinReactionTotal` were moved to `ReactableEloquentBuilderTrait`.

To start using them you have to create custom Eloquent Builder class, use trait in it and declare that it should be used in your model as default query builder in `newEloquentBuilder` method.

```php
/**
 * @method static UserEloquentBuilder query()
 */
class User extends Model
{
    public function newEloquentBuilder($query): UserEloquentBuilder
    {
        return new UserEloquentBuilder($query);
    }
}

class UserEloquentBuilder extends \Illuminate\Database\Eloquent\Builder
{
    use \Cog\Laravel\Love\Reactable\ReactableEloquentBuilderTrait;

    // Other User model local query scopes
}
```

### CODE REVIEW

**Comment by antonkomarev** [comment]
@vesper8 are you using custom Eloquent Builder classes? I'd prefer to go with this soltution. What do you think?

**Comment by vesper8** [comment]
Hrm... @antonkomarev yes actually I am using one because I also use https://github.com/MatanYadaev/laravel-eloquent-spatial

Which requires this as part of its setup

```

    public function newEloquentBuilder($query): SpatialBuilder
    {
        return new SpatialBuilder($query);
    }
```

And my models that are using this, are also Reacters or Reactants so.. if your package also starts requiring this.. I think it's going to cause a really bad conflict and I won't be able to use it.. or.. it will take some weird hacking so I can use both builders somehow?

**Comment by antonkomarev** [comment]
@vesper8 that's why I'm providing this methods as trait for the Eloquent Builder, but not actually builder, to be able to compose them with other methods. I see here 2 ways:
1. Propose to author of laravel-eloquent-spatial package to move those methods to Trait and use it in Builder, to let people compose with their own builders
2. Make new Eloquent Builder in your app which will extend `SpatialBuilder` (since it's not final) and use traits from Love's Eloquent Builders

**Comment by vesper8** [comment]
@anton I like that link of thinking. Worse case if I need to fork or make my own builder and extend it, that won't be an issue.. I can manage that.

**Comment by antonkomarev** [comment]
In this solution I like that all these methods are placed as closer to Query Builder as possible and IDE auto-complete will work out of the box.

**Pull request merged**
