### PR TITLE
Add getters for aggregates job

### PR DESCRIPTION
**Pull request by ujackson**
I'm using Laravel Job events to determine when `IncrementReactionAggregatesJob` or `DecrementReactionAggregatesJob` is processed.

<pre>Queue::after(function (JobProcessed $event) {
  dd(unserialize($event->job->payload()['data']['command']));
});</pre>

This PR allows easily accessing the private properties in the job class.

### CODE REVIEW

**Comment by antonkomarev** [comment]
Thank you for the contribution! Could you provide a use case for it?

**Comment by ujackson** [comment]
> Thank you for the contribution @ujackson! Could you provide a use case for it?

Hello @antonkomarev 

I needed a way to update total counts for certain reactant models. 
Instead of manually loading the service providers as stated here: https://github.com/cybercog/laravel-love/issues/160#issuecomment-615959539, I could easily tap into the job events which gives a more accurate record than overriding the `IncrementAggregates` and `DecrementAggregates` event listeners

**Comment by antonkomarev** [comment]
To be honest by this way application logic become less transparent. As for me hooking into the JobProcessed event is required to send metrics to monitoring or log debug information, but not run synchronization tasks.

**Comment by antonkomarev** [comment]
I've merged it because it might be useful for the debugging reasons, but I suggest you to think about another way to do it.

If you'll stick to your current solution you could use FQCN comparison to simplify class usage search:
```php
$className = $event->job->resolveName();
$className === \Cog\Laravel\Love\Reactant\Jobs\DecrementReactionAggregatesJob::class
```

**Comment by ujackson** [comment]
> I've merged it because it might be useful for the debugging reasons, but I suggest you to think about another way to do it.
> Release will be pushed soon.
> 
> If you'll stick to your current solution you could use FQCN comparison to simplify class usage search:
> 
> ```
> $className = $event->job->resolveName();
> $className === \Cog\Laravel\Love\Reactant\Jobs\DecrementReactionAggregatesJob::class
> ```

Thank you @antonkomarev 

I figured the job events weren't too transparent as you mentioned. 
I created accessors & mutators for the reactant model attributes and I could return computed values with this method.

<pre>
public function getReactionsCount(string $reactionType): int
    {
        return $this
            ->viaLoveReactant()
            ->getReactionCounterOfType($reactionType)
            ->getCount();
    }
</pre>

Thanks for your help. 🙏

**Comment by antonkomarev** [comment]
[Laravel Love v8.6.0](https://github.com/cybercog/laravel-love/releases/tag/8.6.0) has been released.

**Pull request merged**
